In [1]:
# quick review on pandas and what it can do when working with other modules
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt #to get plotting working

In [2]:
lst = [1,2.2,"foo", lambda x:x*2]
print(lst)

[1, 2.2, 'foo', <function <lambda> at 0x7f776b846040>]


In [3]:
ary = np.array([1,2,3,3])
ary

array([1, 2, 3, 3])

In [4]:
ary.dtype

dtype('int64')

In [5]:
type(ary)

numpy.ndarray

In [6]:
ary[0] = 42
ary

array([42,  2,  3,  3])

In [7]:
ary[0]=32.6
ary

array([32,  2,  3,  3])

In [8]:
ary[0] = "foo"

ValueError: invalid literal for int() with base 10: 'foo'

In [9]:
ary.dtype 

dtype('int64')

In [10]:
lst = [1,2,3]
len(lst)

3

In [11]:
np.array([1,2,3]).shape

(3,)

In [12]:
A=[[1,2],[3,4]]

In [16]:
A[0][1]

2

In [17]:
A

[[1, 2], [3, 4]]

In [20]:
A[0,1]
#A.shape

TypeError: list indices must be integers or slices, not tuple

In [21]:
A.shape

AttributeError: 'list' object has no attribute 'shape'

#### Slicing and indexing

In [23]:
A = np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])

In [24]:
A[1,2] # 2nd row, 3rd column 

7

In [25]:
A[0,1] # first row 2nd column

2

In [29]:
A[:1] == A[0] # until the 2nd vs the first row are equivilant

array([[ True,  True,  True,  True]])

In [31]:
A[:,1] # just the decond column 

array([ 2,  6, 10])

In [36]:
A[0:2,:] # the first and second rows

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
A[0]

##### Vecterized Operations